import type { ImportPreview } from "../../core/model";
export const COPY = {
  "zh-CN": {
    title: "Web Ink",
    current: "当前页面",
    pageAnnotations: "本页标注",
    showAnnotations: "显示标注",
    pageEmptyTitle: "留下值得记住的内容",
    pageEmptyText: "选中网页文字，开始第一条标注。",
    moreActions: "更多操作",
    library: "资料库",
    settings: "设置与数据",
    openLibrary: "打开资料库",
    openPdf: "打开 PDF",
    openingPdf: "正在打开…",
    restoreExplanation: "页面内容可能已变化，暂时无法确认原来的标注位置。原标注和笔记仍已保留。",
    rebindTextHint: "点击「重新绑定」，再选中对应文字并选择高亮颜色。",
    rebindImageHint: "点击「重新绑定」后，选择对应图片。",
    localDataNotice: "数据仅保存在当前浏览器。更新、清理浏览器数据或更换设备前，请先下载 JSON 备份；卸载扩展会删除本地数据。",
    currentPdfTitle: "给这份 PDF 留下重点",
    pdfWelcomeTitle: "在 Web Ink 中读 PDF",
    currentPdfText: "在专属阅读器中高亮、框选和记笔记。",
    pdfFallbackText: "选择本地文件，或粘贴 PDF 链接，即可开始标注。",
    openCurrentPdf: "用 Web Ink 打开当前 PDF",
    chooseLocalPdf: "选择本地 PDF",
    pdfLocalNote: "标注保存在本机 · 无需账号",
    refresh: "刷新",
    close: "关闭",
    language: "语言",
    chinese: "中文",
    english: "English",
    defaultColor: "默认颜色",
    theme: "外观",
    system: "跟随系统",
    light: "浅色",
    dark: "深色",
    reduceMotion: "减少动态效果",
    reduceTransparency: "减少透明效果",
    pause: "暂停此网站",
    resume: "恢复此网站",
    paused: "此网站已暂停，现有标注不会显示。",
    enabled: "本页标注已开启",
    disabled: "本页标注已关闭",
    enable: "开启本页标注",
    disable: "关闭本页标注",
    permission: "启用网页访问",
    permissionText: "请允许 Web Ink 访问 HTTP(S) 网页，才能显示和保存标注。",
    unsupported: "当前标签页不支持",
    unsupportedText: "请打开一个 HTTP(S) 网页后再使用 Web Ink。",
    empty: "这个页面还没有标注",
    emptyText: "选中网页文字，或使用图片绘制工具开始。",
    search: "搜索文字、笔记、网址或标签",
    filter: "筛选",
    all: "全部",
    text: "文字",
    image: "图片",
    pdf: "PDF",
    pdfText: "PDF 文字",
    pdfArea: "PDF 区域",
    located: "已定位",
    pending: "等待加载",
    unresolved: "未定位",
    unsupportedStatus: "不支持",
    focus: "定位",
    source: "打开来源",
    rebind: "重新定位",
    draw: "绘制",
    drawImage: "图片绘制",
    save: "保存",
    delete: "删除",
    confirmDelete: "确认删除",
    note: "笔记",
    tags: "标签（以逗号分隔）",
    cancel: "取消",
    updated: "已保存",
    conflict: "该标注已在其他窗口更新。你的草稿仍已保留。",
    loadLatest: "载入最新版本",
    deleteConfirm: "删除这条标注？此操作无法撤销。",
    backup: "备份与导入",
    downloadJson: "下载 JSON",
    downloadMarkdown: "下载 Markdown",
    import: "导入备份",
    chooseFile: "选择 JSON 文件",
    overwrite: "覆盖同 ID 的冲突记录",
    importSettings: "导入文件中的设置不会覆盖本地设置。",
    importSummary: (p: ImportPreview) =>
      `共 ${p.total} 条：新增 ${p.added}，相同 ${p.identical}，冲突 ${p.conflicts}`,
    importing: "正在导入",
    importDone: "导入完成",
    noResults: "没有匹配的标注",
    page: "页面",
    unknownPage: "无法读取当前页面",
    actionUnavailable: "此操作需要当前网页标签页。",
    loadMore: "加载更多",
    loading: "正在加载…",
    color: "颜色",
    tag: "标签",
    clearFilters: "清除筛选",
  },
  en: {
    title: "Web Ink",
    current: "Current page",
    pageAnnotations: "Page annotations",
    showAnnotations: "Show annotations",
    pageEmptyTitle: "Keep what matters",
    pageEmptyText: "Select text on the page to make your first highlight.",
    moreActions: "More actions",
    library: "Library",
    settings: "Settings & data",
    openLibrary: "Open library",
    openPdf: "Open PDF",
    openingPdf: "Opening…",
    restoreExplanation: "The page may have changed, so the original position could not be confirmed. Your annotation and note are retained. ",
    rebindTextHint: "Choose Rebind, then select the matching text and apply a highlight color.",
    rebindImageHint: "Choose Rebind, then select the matching image.",
    localDataNotice: "Data is stored only in this browser. Download a JSON backup before updating, clearing browser data, or changing devices. Uninstalling removes local data.",
    currentPdfTitle: "Keep the important parts",
    pdfWelcomeTitle: "Read PDFs in Web Ink",
    currentPdfText: "Highlight, mark an area, and add notes in your reader.",
    pdfFallbackText: "Choose a local file or paste a PDF link to start annotating.",
    openCurrentPdf: "Open current PDF in Web Ink",
    chooseLocalPdf: "Choose local PDF",
    pdfLocalNote: "Notes stay on this device · No account",
    refresh: "Refresh",
    close: "Close",
    language: "Language",
    chinese: "中文",
    english: "English",
    defaultColor: "Default color",
    theme: "Appearance",
    system: "System",
    light: "Light",
    dark: "Dark",
    reduceMotion: "Reduce motion",
    reduceTransparency: "Reduce transparency",
    pause: "Pause this site",
    resume: "Resume this site",
    paused: "This site is paused; existing annotations are hidden.",
    enabled: "Annotations on for this page",
    disabled: "Annotations off for this page",
    enable: "Enable page annotations",
    disable: "Disable page annotations",
    permission: "Enable page access",
    permissionText:
      "Allow Web Ink to access HTTP(S) pages to show and save annotations.",
    unsupported: "This tab is not supported",
    unsupportedText: "Open an HTTP(S) page to use Web Ink.",
    empty: "No annotations on this page",
    emptyText: "Select text on a page or use the image drawing tool to begin.",
    search: "Search text, notes, URLs, or tags",
    filter: "Filter",
    all: "All",
    text: "Text",
    image: "Image",
    pdf: "PDF",
    pdfText: "PDF text",
    pdfArea: "PDF area",
    located: "Located",
    pending: "Loading",
    unresolved: "Unresolved",
    unsupportedStatus: "Unsupported",
    focus: "Focus",
    source: "Open source",
    rebind: "Rebind",
    draw: "Draw",
    drawImage: "Draw image",
    save: "Save",
    delete: "Delete",
    confirmDelete: "Confirm delete",
    note: "Note",
    tags: "Tags (comma separated)",
    cancel: "Cancel",
    updated: "Saved",
    conflict:
      "This annotation changed in another window. Your draft is still here.",
    loadLatest: "Load latest version",
    deleteConfirm: "Delete this annotation? This cannot be undone.",
    backup: "Backup & import",
    downloadJson: "Download JSON",
    downloadMarkdown: "Download Markdown",
    import: "Import backup",
    chooseFile: "Choose JSON file",
    overwrite: "Overwrite conflicting IDs",
    importSettings: "Settings in an import never replace local settings.",
    importSummary: (p: ImportPreview) =>
      `${p.total} total: ${p.added} new, ${p.identical} identical, ${p.conflicts} conflicts`,
    importing: "Importing",
    importDone: "Import complete",
    noResults: "No matching annotations",
    page: "Page",
    unknownPage: "Cannot read the active page",
    actionUnavailable: "This action needs an active web tab.",
    loadMore: "Load more",
    loading: "Loading…",
    color: "Color",
    tag: "Tag",
    clearFilters: "Clear filters",
  },
} as const;
