import { useCallback, useEffect, useRef, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { toMarkdown } from '../core/backup';
import { request } from '../core/client';
import { COLORS, DEFAULT_SETTINGS, type AnchorState, type Annotation, type AnnotationPage, type AnnotationQuery, type BackupEnvelope, type ImportPreview, type Language, type Settings } from '../core/model';
import { isWebPage, pageKey } from '../core/url';
import { ICON_PATHS, type IconName } from './icons';
import { StoragePanel } from './StoragePanel';
import { THEME_TOKENS } from './theme';
import './management.css';

type Mode = 'sidepanel' | 'library';
type Screen = 'library' | 'settings';
type TabContext = { id?: number; url?: string; title?: string };
type Draft = { note: string; tags: string; color: string; base: Annotation };
type AnnotationKind = Annotation['kind'];
type FilterKind = 'all' | AnnotationKind;
type NoticeMessage = { type?: string; tabId?: number; pageUrl?: string; annotation?: Annotation; deletedId?: string };

const COPY = {
  'zh-CN': {
    title: 'Web Ink', current: '当前页面', library: '资料库', settings: '设置与数据', openLibrary: '打开资料库', openPdf: '打开 PDF', refresh: '刷新', close: '关闭', language: '语言', chinese: '中文', english: 'English', defaultColor: '默认颜色', theme: '外观', system: '跟随系统', light: '浅色', dark: '深色', reduceMotion: '减少动态效果', reduceTransparency: '减少透明效果', pause: '暂停此网站', resume: '恢复此网站', paused: '此网站已暂停，现有标注不会显示。', enabled: '本页标注已开启', disabled: '本页标注已关闭', enable: '开启本页标注', disable: '关闭本页标注', permission: '启用网页访问', permissionText: '请允许 Web Ink 访问 HTTP(S) 网页，才能显示和保存标注。', unsupported: '当前标签页不支持', unsupportedText: '请打开一个 HTTP(S) 网页后再使用 Web Ink。', empty: '这个页面还没有标注', emptyText: '选中网页文字，或使用图片绘制工具开始。', search: '搜索文字、笔记、网址或标签', filter: '筛选', all: '全部', text: '文字', image: '图片', pdf: 'PDF', pdfText: 'PDF 文字', pdfArea: 'PDF 区域', located: '已定位', pending: '等待加载', unresolved: '未定位', unsupportedStatus: '不支持', focus: '定位', source: '打开来源', rebind: '重新定位', draw: '绘制', drawImage: '图片绘制', save: '保存', delete: '删除', note: '笔记', tags: '标签（以逗号分隔）', cancel: '取消', updated: '已保存', conflict: '该标注已在其他窗口更新。你的草稿仍已保留。', loadLatest: '载入最新版本', deleteConfirm: '删除这条标注？此操作无法撤销。', backup: '备份与导入', downloadJson: '下载 JSON', downloadMarkdown: '下载 Markdown', import: '导入备份', chooseFile: '选择 JSON 文件', overwrite: '覆盖同 ID 的冲突记录', importSettings: '导入文件中的设置不会覆盖本地设置。', importSummary: (p: ImportPreview) => `共 ${p.total} 条：新增 ${p.added}，相同 ${p.identical}，冲突 ${p.conflicts}`, importing: '正在导入', importDone: '导入完成', noResults: '没有匹配的标注', page: '页面', unknownPage: '无法读取当前页面', actionUnavailable: '此操作需要当前网页标签页。', loadMore: '加载更多', loading: '正在加载…', color: '颜色', tag: '标签', clearFilters: '清除筛选',
  },
  en: {
    title: 'Web Ink', current: 'Current page', library: 'Library', settings: 'Settings & data', openLibrary: 'Open library', openPdf: 'Open PDF', refresh: 'Refresh', close: 'Close', language: 'Language', chinese: '中文', english: 'English', defaultColor: 'Default color', theme: 'Appearance', system: 'System', light: 'Light', dark: 'Dark', reduceMotion: 'Reduce motion', reduceTransparency: 'Reduce transparency', pause: 'Pause this site', resume: 'Resume this site', paused: 'This site is paused; existing annotations are hidden.', enabled: 'Annotations on for this page', disabled: 'Annotations off for this page', enable: 'Enable page annotations', disable: 'Disable page annotations', permission: 'Enable page access', permissionText: 'Allow Web Ink to access HTTP(S) pages to show and save annotations.', unsupported: 'This tab is not supported', unsupportedText: 'Open an HTTP(S) page to use Web Ink.', empty: 'No annotations on this page', emptyText: 'Select text on a page or use the image drawing tool to begin.', search: 'Search text, notes, URLs, or tags', filter: 'Filter', all: 'All', text: 'Text', image: 'Image', pdf: 'PDF', pdfText: 'PDF text', pdfArea: 'PDF area', located: 'Located', pending: 'Loading', unresolved: 'Unresolved', unsupportedStatus: 'Unsupported', focus: 'Focus', source: 'Open source', rebind: 'Rebind', draw: 'Draw', drawImage: 'Draw image', save: 'Save', delete: 'Delete', note: 'Note', tags: 'Tags (comma separated)', cancel: 'Cancel', updated: 'Saved', conflict: 'This annotation changed in another window. Your draft is still here.', loadLatest: 'Load latest version', deleteConfirm: 'Delete this annotation? This cannot be undone.', backup: 'Backup & import', downloadJson: 'Download JSON', downloadMarkdown: 'Download Markdown', import: 'Import backup', chooseFile: 'Choose JSON file', overwrite: 'Overwrite conflicting IDs', importSettings: 'Settings in an import never replace local settings.', importSummary: (p: ImportPreview) => `${p.total} total: ${p.added} new, ${p.identical} identical, ${p.conflicts} conflicts`, importing: 'Importing', importDone: 'Import complete', noResults: 'No matching annotations', page: 'Page', unknownPage: 'Cannot read the active page', actionUnavailable: 'This action needs an active web tab.', loadMore: 'Load more', loading: 'Loading…', color: 'Color', tag: 'Tag', clearFilters: 'Clear filters',
  },
} as const;

function tagText(tags: string[]): string { return tags.join(', '); }
function parseTags(value: string): string[] { return [...new Set(value.split(',').map(tag => tag.trim()).filter(Boolean))]; }
function statusClass(status: AnchorState['status'] | undefined): string { return `status ${status ?? 'pending'}`; }
function annotationText(annotation: Annotation): string { const target = annotation.kind === 'text' ? annotation.target.exact : annotation.kind === 'image' ? `${annotation.target.alt} ${annotation.target.context} ${annotation.target.src}` : `${annotation.target.fileName} ${annotation.target.sourceUrl ?? ''} ${annotation.target.exact}`; return `${annotation.pageTitle} ${annotation.pageUrl} ${annotation.note} ${annotation.tags.join(' ')} ${target}`.toLocaleLowerCase(); }
function matchesQuery(annotation: Annotation, query: { pageUrl?: string; kind: FilterKind; color: string; tag: string; text: string }): boolean { return (!query.pageUrl || annotation.pageUrl === query.pageUrl) && (query.kind === 'all' || annotation.kind === query.kind) && (!query.color || annotation.color === query.color) && (!query.tag || annotation.tags.includes(query.tag)) && (!query.text || annotationText(annotation).includes(query.text.toLocaleLowerCase())); }
function isPdf(annotation: Annotation): annotation is Extract<Annotation, { kind: 'pdf-text' | 'pdf-area' }> { return annotation.kind === 'pdf-text' || annotation.kind === 'pdf-area'; }
export function pdfReaderUrl(readerBase: string, record?: Annotation): string { const url = new URL(readerBase); if (record && isPdf(record)) { url.searchParams.set('document', record.target.documentHash); if (record.target.sourceUrl) url.searchParams.set('source', record.target.sourceUrl); } return url.href; }
function kindFamily(kind: AnnotationKind): 'text' | 'image' | 'pdf' { return kind === 'text' ? 'text' : kind === 'image' ? 'image' : 'pdf'; }
function localDate(value: string, language: Language): string { const date = new Date(value); return Number.isNaN(date.valueOf()) ? value : new Intl.DateTimeFormat(language === 'zh-CN' ? 'zh-CN' : 'en', { dateStyle: 'medium', timeStyle: 'short' }).format(date); }
function download(name: string, content: string, type: string): void { const url = URL.createObjectURL(new Blob([content], { type })); const anchor = document.createElement('a'); anchor.href = url; anchor.download = name; anchor.click(); setTimeout(() => URL.revokeObjectURL(url), 0); }
function Icon({ name }: { name: IconName }) { return <svg className="icon" viewBox="0 0 24 24" aria-hidden="true" focusable="false"><path d={ICON_PATHS[name]} /></svg>; }

export function mountManagementApp(root: HTMLElement, mode: Mode): void { createRoot(root).render(<ManagementApp mode={mode} />); }

export function ManagementApp({ mode }: { mode: Mode }) {
  const [settings, setSettings] = useState<Settings>(DEFAULT_SETTINGS);
  const [tab, setTab] = useState<TabContext>({});
  const [hasPermission, setHasPermission] = useState(true);
  const [states, setStates] = useState<Record<string, AnchorState>>({});
  const [pageEnabled, setPageEnabled] = useState(false);
  const [records, setRecords] = useState<Annotation[]>([]);
  const [nextCursor, setNextCursor] = useState<AnnotationPage['nextCursor']>();
  const [query, setQuery] = useState(''); const [kind, setKind] = useState<FilterKind>('all'); const [color, setColor] = useState(''); const [tag, setTag] = useState(''); const [filterOpen, setFilterOpen] = useState(false);
  const [screen, setScreen] = useState<Screen>('library'); const [selectedId, setSelectedId] = useState<string>(); const [libraryDetail, setLibraryDetail] = useState(false);
  const [drafts, setDrafts] = useState<Record<string, Draft>>({}); const [editing, setEditing] = useState<string>(); const [conflicts, setConflicts] = useState<Record<string, true>>({});
  const [error, setError] = useState<string>(); const [notice, setNotice] = useState<string>(); const [backup, setBackup] = useState<unknown>(); const [preview, setPreview] = useState<ImportPreview>(); const [overwrite, setOverwrite] = useState(false); const [busyImport, setBusyImport] = useState(false); const [loading, setLoading] = useState(false);
  const queryRequest = useRef<string | undefined>(undefined); const contextRequest = useRef(0); const listContext = useRef(''); const settingsRef = useRef<Settings>(settings); const settingsQueue = useRef<Promise<void>>(Promise.resolve()); const settingsVersion = useRef(0); const pendingSettings = useRef(0); settingsRef.current = settings; const language = settings.language; const t = COPY[language]; const pageUrl = tab.url && isWebPage(tab.url) ? pageKey(tab.url) : undefined; const origin = pageUrl ? new URL(pageUrl).origin : undefined; const paused = Boolean(origin && settings.disabledOrigins.includes(origin)); const listKey = JSON.stringify({ mode, pageUrl: mode === 'sidepanel' ? pageUrl : undefined, kind, color, tag, query }); listContext.current = listKey;

  const pageState = useCallback(async (tabId?: number, url?: string, expectedContext?: number) => {
    if (mode !== 'sidepanel' || tabId === undefined || !url) { setStates({}); setPageEnabled(false); return; }
    try { const result = await request<{ pageUrl?: string; states: AnchorState[]; enabled?: boolean }>({ type: 'page.state.get', tabId }); if ((expectedContext !== undefined && expectedContext !== contextRequest.current) || (result.pageUrl && result.pageUrl !== url)) return; const next: Record<string, AnchorState> = {}; for (const state of result.states) next[state.id] = state; setStates(next); setPageEnabled(result.enabled === true); } catch (cause) { if (expectedContext === undefined || expectedContext === contextRequest.current) setError(cause instanceof Error ? cause.message : String(cause)); }
  }, [mode]);
  const loadRecords = useCallback(async (append = false, cursor?: AnnotationPage['nextCursor']) => {
    if (mode === 'sidepanel' && !pageUrl) { setRecords([]); setNextCursor(undefined); setLoading(false); return; }
    const requestId = crypto.randomUUID(), obsolete = queryRequest.current; queryRequest.current = requestId; if (obsolete) void request({ type: 'annotations.query.cancel', requestId: obsolete }).catch(() => undefined); setLoading(true);
    const querySpec: AnnotationQuery = { ...(mode === 'sidepanel' && pageUrl ? { pageUrl } : {}), ...(kind === 'all' ? {} : { kind }), ...(color ? { color } : {}), ...(tag ? { tag } : {}), ...(query.trim() ? { text: query.trim() } : {}), ...(cursor ? { cursor } : {}), limit: 50, requestId };
    const requestedListKey = listKey;
    try { const page = await request<AnnotationPage>({ type: 'annotations.query', query: querySpec }); if (queryRequest.current !== requestId || listContext.current !== requestedListKey || page.cancelled) return; setRecords(current => append ? [...current, ...page.items.filter(item => !current.some(old => old.id === item.id))] : page.items); setNextCursor(page.nextCursor); if (!append) setSelectedId(current => page.items.some(item => item.id === current) ? current : page.items[0]?.id); } catch (cause) { if (queryRequest.current === requestId && listContext.current === requestedListKey) setError(cause instanceof Error ? cause.message : String(cause)); } finally { if (queryRequest.current === requestId) setLoading(false); }
  }, [color, kind, mode, pageUrl, query, tag]);
  const refreshContext = useCallback(async () => {
    const requestId = ++contextRequest.current;
    try { const nextTab = mode === 'sidepanel' ? (await chrome.tabs.query({ active: true, currentWindow: true }))[0] : undefined; const context: TabContext = nextTab ? { id: nextTab.id, url: nextTab.url, title: nextTab.title } : {}; const permission = await chrome.permissions.contains({ origins: ['http://*/*', 'https://*/*'] }); const nextSettings = await request<Settings>({ type: 'settings.get' }); if (requestId !== contextRequest.current) return; setTab(context); setHasPermission(permission); settingsRef.current = nextSettings; setSettings(nextSettings); const nextUrl = context.url && isWebPage(context.url) ? pageKey(context.url) : undefined; await pageState(context.id, nextUrl, requestId); } catch (cause) { if (requestId === contextRequest.current) setError(cause instanceof Error ? cause.message : String(cause)); }
  }, [mode, pageState]);
  useEffect(() => { void refreshContext(); }, [refreshContext]);
  useEffect(() => { const timer = setTimeout(() => { void loadRecords(); }, query ? 180 : 0); return () => clearTimeout(timer); }, [loadRecords, query]);
  useEffect(() => () => { if (queryRequest.current) void request({ type: 'annotations.query.cancel', requestId: queryRequest.current }).catch(() => undefined); }, []);
  useEffect(() => {
    const listener = (message: NoticeMessage) => { if (message.type === 'page.state.changed' && mode === 'sidepanel' && message.tabId === tab.id) { void pageState(tab.id, pageUrl, contextRequest.current); return; } if (message.type === 'page.mode.changed' && mode === 'sidepanel' && message.pageUrl === pageUrl) { void pageState(tab.id, pageUrl, contextRequest.current); return; } if (message.type === 'settings.changed') { if (pendingSettings.current) return; void request<Settings>({ type: 'settings.get' }).then(next => { if (!pendingSettings.current) { settingsRef.current = next; setSettings(next); } }).catch(() => undefined); return; } if (message.type !== 'annotations.changed') return; if (message.deletedId) { setRecords(current => current.filter(record => record.id !== message.deletedId)); return; } if (message.annotation) { const active = { pageUrl: mode === 'sidepanel' ? pageUrl : undefined, kind, color, tag, text: query }; if (!matchesQuery(message.annotation, active)) { setRecords(current => current.filter(record => record.id !== message.annotation!.id)); return; } void loadRecords(); return; } void loadRecords(); };
    chrome.runtime.onMessage.addListener(listener); const activated = () => { if (mode === 'sidepanel') void refreshContext(); }; const updated = (_id: number, change: { url?: string }) => { if (mode === 'sidepanel' && change.url) void refreshContext(); }; chrome.tabs.onActivated.addListener(activated); chrome.tabs.onUpdated.addListener(updated); return () => { chrome.runtime.onMessage.removeListener(listener); chrome.tabs.onActivated.removeListener(activated); chrome.tabs.onUpdated.removeListener(updated); };
  }, [color, kind, loadRecords, mode, pageState, pageUrl, query, refreshContext, tab.id, tag]);

  const saveSettings = (patch: Partial<Settings>) => { const next = { ...settingsRef.current, ...patch }; const version = ++settingsVersion.current; settingsRef.current = next; pendingSettings.current++; setSettings(next); settingsQueue.current = settingsQueue.current.catch(() => undefined).then(async () => { try { const saved = await request<Settings>({ type: 'settings.put', settings: next }); if (version === settingsVersion.current) { settingsRef.current = saved; setSettings(saved); } } catch (cause) { if (version === settingsVersion.current) setError(cause instanceof Error ? cause.message : String(cause)); } finally { pendingSettings.current--; } }); };
  const enablePermissions = async () => { try { const granted = await chrome.permissions.request({ origins: ['http://*/*', 'https://*/*'] }); if (!granted) throw new Error(language === 'zh-CN' ? '未授予网页访问权限。' : 'Page access was not granted.'); await request<boolean>({ type: 'permissions.enable' }); await refreshContext(); } catch (cause) { setError(cause instanceof Error ? cause.message : String(cause)); } };
  const pageAction = async (action: 'focus' | 'rebind' | 'draw', id?: string) => { if (tab.id === undefined) { setError(t.actionUnavailable); return; } try { await request<boolean>({ type: 'page.action', tabId: tab.id, action, ...(id ? { id } : {}) }); } catch (cause) { setError(cause instanceof Error ? cause.message : String(cause)); } };
  const toggleCurrentPage = async () => { if (!pageUrl) return; try { await request({ type: 'page.mode.put', pageUrl, enabled: !pageEnabled }); await pageState(tab.id, pageUrl, contextRequest.current); } catch (cause) { setError(cause instanceof Error ? cause.message : String(cause)); } };
  const startEdit = (record: Annotation) => { setEditing(record.id); setDrafts(current => ({ ...current, [record.id]: current[record.id] ?? { note: record.note, tags: tagText(record.tags), color: record.color, base: record } })); };
  const updateDraft = (id: string, patch: Pick<Partial<Draft>, 'note' | 'tags' | 'color'>) => setDrafts(current => current[id] ? ({ ...current, [id]: { ...current[id], ...patch } }) : current);
  const saveRecord = async (id: string) => { const draft = drafts[id]; if (!draft) return; try { const candidate: Annotation = { ...draft.base, note: draft.note, tags: parseTags(draft.tags), color: draft.color, updatedAt: new Date().toISOString() }; const saved = await request<Annotation>({ type: 'annotations.put', annotation: candidate, expectedRevision: draft.base.revision }); setRecords(current => current.map(item => item.id === saved.id ? saved : item)); setDrafts(current => { const { [id]: _removed, ...rest } = current; return rest; }); setConflicts(current => { const { [id]: _removed, ...rest } = current; return rest; }); setEditing(undefined); setNotice(t.updated); } catch (cause) { const message = cause instanceof Error ? cause.message : String(cause); if (/changed in another tab|CONFLICT/i.test(message)) { setConflicts(current => ({ ...current, [id]: true })); setError(t.conflict); void loadRecords(); } else setError(message); } };
  const loadLatest = async (id: string) => { const draft = drafts[id]; if (!draft) return; try { const latest = await request<AnnotationPage>({ type: 'annotations.query', query: { ...(mode === 'sidepanel' && pageUrl ? { pageUrl } : {}), text: '', limit: 50, requestId: crypto.randomUUID() } }); const record = latest.items.find(item => item.id === id); if (!record) throw new Error(language === 'zh-CN' ? '标注已被删除。' : 'The annotation was deleted.'); setRecords(current => current.map(item => item.id === id ? record : item)); setDrafts(current => current[id] ? ({ ...current, [id]: { ...current[id], base: record } }) : current); setConflicts(current => { const { [id]: _removed, ...rest } = current; return rest; }); } catch (cause) { setError(cause instanceof Error ? cause.message : String(cause)); } };
  const removeRecord = async (record: Annotation) => { if (!window.confirm(t.deleteConfirm)) return; try { await request<{ id: string; deleted: true }>({ type: 'annotations.delete', id: record.id, expectedRevision: record.revision }); setRecords(current => current.filter(item => item.id !== record.id)); if (selectedId === record.id) setSelectedId(undefined); } catch (cause) { setError(cause instanceof Error ? cause.message : String(cause)); } };
  const exportJson = async () => { try { const value = await request<BackupEnvelope>({ type: 'backup.export' }); download('web-ink-backup.json', JSON.stringify(value), 'application/json'); } catch (cause) { setError(cause instanceof Error ? cause.message : String(cause)); } };
  const exportMarkdown = async () => { try { const value = await request<BackupEnvelope>({ type: 'backup.export' }); download('web-ink-annotations.md', toMarkdown(value.annotations), 'text/markdown;charset=utf-8'); } catch (cause) { setError(cause instanceof Error ? cause.message : String(cause)); } };
  const readImport = async (file: File | undefined) => { if (!file) return; if (file.size > 20 * 1024 * 1024) { setError('Import file exceeds 20 MiB.'); return; } try { const value: unknown = JSON.parse(await file.text()); const nextPreview = await request<ImportPreview>({ type: 'backup.preview', backup: value }); setBackup(value); setPreview(nextPreview); setError(undefined); } catch (cause) { setBackup(undefined); setPreview(undefined); setError(cause instanceof Error ? cause.message : String(cause)); } };
  const importBackup = async () => { if (!backup) return; setBusyImport(true); try { await request<ImportPreview>({ type: 'backup.import', backup, overwrite }); setNotice(t.importDone); setBackup(undefined); setPreview(undefined); await loadRecords(); } catch (cause) { setError(cause instanceof Error ? cause.message : String(cause)); } finally { setBusyImport(false); } };
  const openPdf = (record?: Annotation) => { window.open(pdfReaderUrl(chrome.runtime.getURL('/pdf.html'), record)); };
  const filterCount = Number(kind !== 'all') + Number(Boolean(color)) + Number(Boolean(tag));
  const explicitTheme = settings.theme === 'light' || settings.theme === 'dark' ? settings.theme : undefined;
  return <main className="ink-app" style={explicitTheme ? THEME_TOKENS[explicitTheme] as React.CSSProperties : undefined} data-theme={settings.theme ?? 'system'} data-reduce-motion={settings.reduceMotion === true} data-reduce-transparency={settings.reduceTransparency === true}>
    <header className="topbar"><div className="app-title"><p className="eyebrow">LOCAL WEB NOTES</p><h1>{mode === 'sidepanel' ? t.current : screen === 'settings' ? t.settings : t.library}</h1></div><div className="header-actions">{mode === 'sidepanel' ? <button className="quiet" onClick={() => window.open(chrome.runtime.getURL('library.html'))}><Icon name="library" />{t.openLibrary}</button> : <><button className={screen === 'library' ? 'segmented selected' : 'segmented'} onClick={() => setScreen('library')}><Icon name="library" />{t.library}</button><button className={screen === 'settings' ? 'segmented selected' : 'segmented'} onClick={() => setScreen('settings')}><Icon name="settings" />{t.settings}</button></>}{mode === 'library' && screen === 'library' ? <button className="quiet" onClick={() => openPdf()}><Icon name="pdf" />{t.openPdf}</button> : null}<button className="icon-button" onClick={() => { void refreshContext(); void loadRecords(); }} aria-label={t.refresh} title={t.refresh}><Icon name="refresh" /></button></div></header>
    {error ? <Alert kind="error" text={error} close={() => setError(undefined)} closeLabel={t.close} /> : null}{notice ? <Alert kind="notice" text={notice} close={() => setNotice(undefined)} closeLabel={t.close} /> : null}
    {!hasPermission ? <Empty title={t.permission} text={t.permissionText} action={<button className="primary" onClick={() => void enablePermissions()}>{t.permission}</button>} /> : null}
    {hasPermission && mode === 'sidepanel' ? <><PageHeader title={pageUrl ? (tab.title || new URL(pageUrl).host) : t.unknownPage} host={pageUrl ? new URL(pageUrl).host : undefined} enabled={pageEnabled} onToggle={toggleCurrentPage} toggleLabel={pageEnabled ? t.disable : t.enable} />{!pageUrl ? <Empty title={t.unsupported} text={t.unsupportedText} /> : paused ? <section className="notice-card warning"><strong>{t.paused}</strong><button className="quiet" onClick={() => saveSettings({ disabledOrigins: settingsRef.current.disabledOrigins.filter(item => item !== origin) })}>{t.resume}</button></section> : <div className="page-actions"><button className="primary" onClick={() => void pageAction('draw')}><Icon name="draw" />{t.drawImage}</button><details className="menu"><summary aria-label={t.settings}><Icon name="more" /></summary><button className="danger" onClick={() => saveSettings({ disabledOrigins: origin ? [...settingsRef.current.disabledOrigins, origin] : settingsRef.current.disabledOrigins })}>{t.pause}</button></details></div>}{pageUrl && !paused ? <AnnotationBrowser compact records={records} selectedId={selectedId} setSelectedId={setSelectedId} states={states} language={language} t={t} editing={editing} drafts={drafts} conflicts={conflicts} onEdit={startEdit} onDraft={updateDraft} onSave={saveRecord} onLoadLatest={loadLatest} onCancel={() => setEditing(undefined)} onDelete={removeRecord} onFocus={record => void pageAction('focus', record.id)} onRebind={record => void pageAction('rebind', record.id)} onDraw={record => void pageAction('draw', record.id)} onOpenPdf={openPdf} /> : null}{nextCursor && !loading && pageUrl && !paused ? <button className="load-more" onClick={() => void loadRecords(true, nextCursor)}>{t.loadMore}</button> : null}{pageUrl && !records.length && !loading && !paused ? <Empty title={t.empty} text={t.emptyText} /> : null}</> : null}
    {hasPermission && mode === 'library' && screen === 'library' ? <section className="library-shell"><div className="library-tools"><label className="search"><Icon name="search" /><input aria-label={t.search} value={query} onChange={event => setQuery(event.target.value)} placeholder={t.search} /></label><button className={filterOpen ? 'quiet selected' : 'quiet'} aria-expanded={filterOpen} onClick={() => setFilterOpen(value => !value)}><Icon name="filter" />{t.filter}{filterCount ? <span className="filter-count">{filterCount}</span> : null}</button>{filterOpen ? <FilterPopover language={language} t={t} kind={kind} color={color} tag={tag} records={records} setKind={setKind} setColor={setColor} setTag={setTag} clear={() => { setKind('all'); setColor(''); setTag(''); }} /> : null}</div><AnnotationBrowser detailOpen={libraryDetail} onBack={() => setLibraryDetail(false)} records={records} selectedId={selectedId} setSelectedId={id => { setSelectedId(id); setLibraryDetail(true); }} states={states} language={language} t={t} editing={editing} drafts={drafts} conflicts={conflicts} onEdit={startEdit} onDraft={updateDraft} onSave={saveRecord} onLoadLatest={loadLatest} onCancel={() => setEditing(undefined)} onDelete={removeRecord} onFocus={() => undefined} onRebind={() => undefined} onDraw={() => undefined} onOpenPdf={openPdf} />{!records.length && !loading ? <Empty title={query || filterCount ? t.noResults : t.empty} text="" /> : null}{loading ? <p className="loading" role="status">{t.loading}</p> : null}{nextCursor && !loading ? <button className="load-more" onClick={() => void loadRecords(true, nextCursor)}>{t.loadMore}</button> : null}</section> : null}
    {hasPermission && mode === 'library' && screen === 'settings' ? <SettingsView settings={settings} t={t} language={language} saveSettings={saveSettings} exportJson={exportJson} exportMarkdown={exportMarkdown} readImport={readImport} preview={preview} overwrite={overwrite} setOverwrite={setOverwrite} busyImport={busyImport} importBackup={importBackup} /> : null}
  </main>;
}

function Alert({ kind, text, close, closeLabel }: { kind: 'error' | 'notice'; text: string; close: () => void; closeLabel: string }) { return <p className={`alert ${kind}`} role={kind === 'error' ? 'alert' : 'status'}>{text}<button onClick={close} aria-label={closeLabel}><Icon name="close" /></button></p>; }
function Empty({ title, text, action }: { title: string; text: string; action?: React.ReactNode }) { return <section className="empty"><h2>{title}</h2>{text ? <p>{text}</p> : null}{action ? <div>{action}</div> : null}</section>; }
function PageHeader({ title, host, enabled, onToggle, toggleLabel }: { title: string; host?: string; enabled: boolean; onToggle: () => void; toggleLabel: string }) { return <section className="page-header"><div><p className="eyebrow">CURRENT PAGE</p><strong title={title}>{title}</strong>{host ? <span>{host}</span> : null}</div><button className={enabled ? 'page-switch on' : 'page-switch'} aria-pressed={enabled} onClick={onToggle}><span aria-hidden="true" />{toggleLabel}</button></section>; }
function FilterPopover({ language, t, kind, color, tag, records, setKind, setColor, setTag, clear }: { language: Language; t: typeof COPY[Language]; kind: FilterKind; color: string; tag: string; records: Annotation[]; setKind: (value: FilterKind) => void; setColor: (value: string) => void; setTag: (value: string) => void; clear: () => void }) { const colors = [...new Set(records.map(record => record.color))].sort(); const tags = [...new Set(records.flatMap(record => record.tags))].sort(); return <section className="filter-popover" aria-label={t.filter}><div className="filter-kinds" role="group" aria-label={t.filter}>{(['all', 'text', 'image', 'pdf-text', 'pdf-area'] as const).map(value => <button key={value} className={kind === value ? 'selected' : ''} onClick={() => setKind(value)}>{value === 'all' ? t.all : value === 'pdf-text' ? t.pdfText : value === 'pdf-area' ? t.pdfArea : value === 'text' ? t.text : t.image}</button>)}</div><label>{t.color}<select value={color} onChange={event => setColor(event.target.value)}><option value="">{t.all}</option>{colors.map(value => <option key={value} value={value}>{value}</option>)}</select></label><label>{t.tag}<select value={tag} onChange={event => setTag(event.target.value)}><option value="">{t.all}</option>{tags.map(value => <option key={value} value={value}>{value}</option>)}</select></label><button className="quiet" onClick={clear}>{t.clearFilters}</button></section>; }
type BrowserProps = { compact?: boolean; detailOpen?: boolean; onBack?: () => void; records: Annotation[]; selectedId?: string; setSelectedId: (id: string) => void; states: Record<string, AnchorState>; language: Language; t: typeof COPY[Language]; editing?: string; drafts: Record<string, Draft>; conflicts: Record<string, true>; onEdit: (record: Annotation) => void; onDraft: (id: string, patch: Pick<Partial<Draft>, 'note' | 'tags' | 'color'>) => void; onSave: (id: string) => void; onLoadLatest: (id: string) => void; onCancel: () => void; onDelete: (record: Annotation) => void; onFocus: (record: Annotation) => void; onRebind: (record: Annotation) => void; onDraw: (record: Annotation) => void; onOpenPdf: (record?: Annotation) => void };
function AnnotationBrowser({ compact = false, detailOpen = false, onBack, records, selectedId, setSelectedId, states, language, t, editing, drafts, conflicts, onEdit, onDraft, onSave, onLoadLatest, onCancel, onDelete, onFocus, onRebind, onDraw, onOpenPdf }: BrowserProps) { const selected = records.find(record => record.id === selectedId) ?? records[0]; return <section className={`${compact ? 'annotation-browser compact' : 'annotation-browser'}${detailOpen ? ' detail-open' : ''}`}><div className="annotation-list" aria-label={t.library}>{records.map(record => <AnnotationRow key={record.id} record={record} selected={selected?.id === record.id} state={states[record.id]} language={language} onSelect={() => setSelectedId(record.id)} />)}</div>{selected ? <AnnotationDetail record={selected} state={states[selected.id]} language={language} t={t} compact={compact} back={onBack} draft={drafts[selected.id]} editing={editing === selected.id} conflict={Boolean(conflicts[selected.id])} onEdit={() => onEdit(selected)} onDraft={patch => onDraft(selected.id, patch)} onSave={() => onSave(selected.id)} onLoadLatest={() => onLoadLatest(selected.id)} onCancel={onCancel} onDelete={() => onDelete(selected)} onFocus={() => onFocus(selected)} onRebind={() => onRebind(selected)} onDraw={() => onDraw(selected)} onOpenPdf={() => onOpenPdf(selected)} /> : null}</section>; }
function AnnotationRow({ record, selected, state, language, onSelect }: { record: Annotation; selected: boolean; state?: AnchorState; language: Language; onSelect: () => void }) { const description = record.kind === 'text' ? record.target.exact : record.kind === 'image' ? record.target.alt || record.target.context || record.target.src : record.target.exact || record.target.fileName; const icon = kindFamily(record.kind) === 'text' ? 'text' : kindFamily(record.kind) === 'image' ? 'image' : 'pdf'; return <button className={selected ? 'annotation-row selected' : 'annotation-row'} onClick={onSelect} style={{ '--record-color': record.color } as React.CSSProperties}><span className="type"><Icon name={icon} /></span><span className="row-copy"><strong>{description}</strong><small>{record.pageTitle || (isPdf(record) ? record.target.fileName : new URL(record.pageUrl).host)} · {localDate(record.updatedAt, language)}</small></span>{state ? <span className={statusClass(state.status)} title={state.reason}>{state.status}</span> : <Icon name="chevron" />}</button>; }
function AnnotationDetail({ record, state, language, t, compact, back, draft, editing, conflict, onEdit, onDraft, onSave, onLoadLatest, onCancel, onDelete, onFocus, onRebind, onDraw, onOpenPdf }: { record: Annotation; state?: AnchorState; language: Language; t: typeof COPY[Language]; compact: boolean; back?: () => void; draft?: Draft; editing: boolean; conflict: boolean; onEdit: () => void; onDraft: (patch: Pick<Partial<Draft>, 'note' | 'tags' | 'color'>) => void; onSave: () => void; onLoadLatest: () => void; onCancel: () => void; onDelete: () => void; onFocus: () => void; onRebind: () => void; onDraw: () => void; onOpenPdf: () => void }) { const label = state ? t[state.status === 'located' ? 'located' : state.status === 'pending' ? 'pending' : state.status === 'unresolved' ? 'unresolved' : 'unsupportedStatus'] : undefined; return <article className={compact ? 'annotation-detail compact' : 'annotation-detail'}>{back ? <button className="back-button quiet" onClick={back}><Icon name="chevron" />{t.library}</button> : null}<div className="detail-heading"><span className="color-dot" style={{ backgroundColor: record.color }} /><div><p className="eyebrow">{kindFamily(record.kind) === 'pdf' ? t.pdf : kindFamily(record.kind) === 'text' ? t.text : t.image}</p><h2>{record.pageTitle || (isPdf(record) ? record.target.fileName : new URL(record.pageUrl).host)}</h2></div>{label ? <span className={statusClass(state?.status)} title={state?.reason}>{label}</span> : null}</div>{editing && draft ? <Editor draft={draft} t={t} conflict={conflict} onDraft={onDraft} onSave={onSave} onLoadLatest={onLoadLatest} onCancel={onCancel} /> : <><p className="detail-excerpt">{record.kind === 'text' ? record.target.exact : record.kind === 'image' ? record.target.alt || record.target.context || record.target.src : record.target.exact || record.target.fileName}</p>{record.note ? <p className="note">{record.note}</p> : null}{record.tags.length ? <div className="tags">{record.tags.map(item => <span key={item}>#{item}</span>)}</div> : null}<div className="detail-actions">{isPdf(record) ? <button onClick={onOpenPdf}><Icon name="pdf" />{t.openPdf}</button> : compact ? <button onClick={onFocus}><Icon name="focus" />{t.focus}</button> : <a href={record.pageUrl} target="_blank" rel="noreferrer"><Icon name="focus" />{t.source}</a>}{state?.status === 'unresolved' && compact ? <button onClick={onRebind}>{t.rebind}</button> : null}{record.kind === 'image' && compact ? <button onClick={onDraw}><Icon name="draw" />{t.draw}</button> : null}<button onClick={onEdit}>{t.note}</button><button className="danger" onClick={onDelete}>{t.delete}</button></div></>}</article>; }
function Editor({ draft, t, conflict, onDraft, onSave, onLoadLatest, onCancel }: { draft: Draft; t: typeof COPY[Language]; conflict: boolean; onDraft: (patch: Pick<Partial<Draft>, 'note' | 'tags' | 'color'>) => void; onSave: () => void; onLoadLatest: () => void; onCancel: () => void }) { return <div className="editor"><label>{t.note}<textarea value={draft.note} onChange={event => onDraft({ note: event.target.value })} maxLength={10_000} /></label><label>{t.tags}<input value={draft.tags} onChange={event => onDraft({ tags: event.target.value })} /></label><ColorPicker value={draft.color} onChange={color => onDraft({ color })} label={t.defaultColor} />{conflict ? <p className="draft-conflict">{t.conflict} <button className="quiet" onClick={onLoadLatest}>{t.loadLatest}</button></p> : null}<div className="detail-actions"><button className="primary" onClick={onSave}>{t.save}</button><button className="quiet" onClick={onCancel}>{t.cancel}</button></div></div>; }
function ColorPicker({ value, onChange, label = 'Custom color' }: { value: string; onChange: (color: string) => void; label?: string }) { return <span className="colors">{COLORS.map(color => <button key={color} type="button" className={value === color ? 'active' : ''} onClick={() => onChange(color)} style={{ backgroundColor: color }} aria-label={color} title={color} />)}<label className="custom-color"><span>{label}</span><input type="color" value={value} onChange={event => onChange(event.target.value)} aria-label={label} /></label></span>; }
function SettingsView({ settings, t, language, saveSettings, exportJson, exportMarkdown, readImport, preview, overwrite, setOverwrite, busyImport, importBackup }: { settings: Settings; t: typeof COPY[Language]; language: Language; saveSettings: (patch: Partial<Settings>) => void; exportJson: () => void; exportMarkdown: () => void; readImport: (file: File | undefined) => void; preview?: ImportPreview; overwrite: boolean; setOverwrite: (value: boolean) => void; busyImport: boolean; importBackup: () => void }) { return <section className="settings-view"><section className="settings-group"><h2>{t.settings}</h2><label>{t.theme}<select aria-label={t.theme} value={settings.theme ?? 'system'} onChange={event => saveSettings({ theme: event.target.value as Settings['theme'] })}><option value="system">{t.system}</option><option value="light">{t.light}</option><option value="dark">{t.dark}</option></select></label><label>{t.language}<select aria-label={t.language} value={settings.language} onChange={event => saveSettings({ language: event.target.value as Language })}><option value="zh-CN">{t.chinese}</option><option value="en">{t.english}</option></select></label><label className="switch-row"><input aria-label={t.reduceMotion} type="checkbox" checked={settings.reduceMotion === true} onChange={event => saveSettings({ reduceMotion: event.target.checked })} />{t.reduceMotion}</label><label className="switch-row"><input aria-label={t.reduceTransparency} type="checkbox" checked={settings.reduceTransparency === true} onChange={event => saveSettings({ reduceTransparency: event.target.checked })} />{t.reduceTransparency}</label><label>{t.defaultColor}<ColorPicker value={settings.defaultColor} onChange={color => saveSettings({ defaultColor: color })} label={t.defaultColor} /></label></section><StoragePanel language={language} /><section className="settings-group"><h2>{t.backup}</h2><div className="detail-actions"><button className="quiet" onClick={exportJson}>{t.downloadJson}</button><button className="quiet" onClick={exportMarkdown}>{t.downloadMarkdown}</button></div><label className="file-input">{t.chooseFile}<input type="file" accept="application/json,.json" onChange={event => void readImport(event.target.files?.[0])} /></label>{preview ? <div className="import-preview"><p>{t.importSummary(preview)}</p><label className="switch-row"><input type="checkbox" checked={overwrite} onChange={event => setOverwrite(event.target.checked)} /> {t.overwrite}</label><button className="primary" disabled={busyImport} onClick={importBackup}>{busyImport ? t.importing : t.import}</button></div> : null}<p className="hint">{t.importSettings}</p></section></section>; }
