import { readFile, writeFile } from 'node:fs/promises';
import { execFileSync } from 'node:child_process';
import { runtimeFiles, digest, validateRuntimeIntegrity } from './lib/runtime.mjs';
import { packFiles, verifyArchive } from './lib/archive.mjs';
const files = await runtimeFiles('.output/chrome-mv3');
const manifest = validateRuntimeIntegrity(files);
const info = JSON.parse(files['build-info.json'].toString());
const pkg = JSON.parse(await readFile('package.json', 'utf8'));
const head = execFileSync('git', ['rev-parse', 'HEAD'], { encoding: 'utf8' }).trim();
if (manifest.version !== pkg.version || info.version !== pkg.version || info.commit !== head) throw Error('Build is stale: rebuild and validate before packaging');
const workingTreeDirty = execFileSync('git', ['status', '--porcelain', '--untracked-files=normal'], { encoding: 'utf8' }).trim().length > 0;
if (process.argv.includes('--release') && (info.dirty || workingTreeDirty)) throw Error('Release packaging requires a clean tested commit');
const bytes = await packFiles(files);
verifyArchive(bytes, files);
const name = `web-ink-${pkg.version}-chrome.zip`;
await writeFile(`.output/${name}`, bytes);
await writeFile(`.output/${name}.sha256`, `${digest(bytes)}  ${name}\n`);
console.log(`${name}: ${Object.keys(files).length} runtime files verified, sha256 ${digest(bytes)}`);
if (info.dirty) console.log('Working-tree build: local preview only. Rebuild a clean commit before publishing.');
